#!/bin/bash

MY_DOTFILES_DIR="$HOME/.dotfiles"
MY_EDITOR=vi

# Load general and local aliases
source "$MY_DOTFILES_DIR/.aliases"
[[ -s "$MY_DOTFILES_DIR/.aliases.local" ]] && source "$MY_DOTFILES_DIR/.aliases.local"